server:
  port: 9000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sca-web
          uri: lb://sca-web
          predicates:
            - Path=/api/web/**
          filters:
            - StripPrefix=2
        - id: sca-order
          uri: lb://sca-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=2
        - id: sca-stock
          uri: lb://sca-stock
          predicates:
            - Path=/api/stock/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: INFO
